### ISSUE TITLE
Get audio only

### ISSUE THREAD

**Issue by berezovskyi** [Feuermurmel/youtube-podcast-gateway#22]
I don't need the video, because I listen to those videos (conference talks mainly) on the bike. Do you think that building the pipeline for extracting audio from video is the only way?

https://github.com/rg3/youtube-dl#post-processing-options

**Comment by berezovskyi** [comment]
And the most important thing: thank you very much for publishing this application, Michael!

**Comment by berezovskyi** [comment]
cc @likelion

**Comment by berezovskyi** [comment]
I actually figured out how to do what I wanted to accomplish. I had to change the acceptable format list to:

    formats = [139, 249, 250, 171, 140, 251] if self.audio_only else [139, 249, 250, 171, 140, 251, 43]

In other words, I prefer audio independent of whether video is `audio_only`.

**Comment by Feuermurmel** [comment]
I'm not sure, I really get what behaviour you wanted to change. Do you want to get audio-only episodes, even when `audio_only` is set to `False`?

In any case, the source line you cited would probably need some love, maybe by making the two lists configurable because those lists are tailored to what my  iPhone 4 will play and may not be the best selection for everyone.

**Comment by berezovskyi** [comment]
My bad, I misunderstood the option.
