### ISSUE TITLE
Server becomes unreachable when i close connection to remote server

### ISSUE THREAD

**Issue by azakordonets** [Feuermurmel/youtube-podcast-gateway#6]
Hi, i'm using your solution to get podcast from one specific youtube channel. When i connect to my digital ocean droplet and run ./run.sh & command, i'm able to load podcasts from iPhone. But as soon as i close connection to my remote server, podcast cannot load new podcasts any more and i can't reach the server by the address i was able to connect when my connection to remote server was alive. I see in your code that you use server.run_forever(), so in theory it should run ok. What am i missing ? 

Thanks.

**Comment by azakordonets** [comment]
Manage to resolve this by running screen -d -m ./run.sh

**Comment by Feuermurmel** [comment]
Yeah, that might be a problem. The application does not handle any of the complexities of running a daemon in the background. The process will crash as soon as it tires to write to the console after you've closed the SSH connection, as the file used for stdout/stderr will be closed by that time. I myself run it in a tmux session for that reason.

I'm not sure what the right way to solve that problem is. I don't want to have to maintain a SysV init script or similar _just_ to get a process running after the machine boots up.

**Comment by azakordonets** [comment]
And how do you make your server to update list of podcasts? I have my server running in screen, but what i find is that in my podcast app on iphone list is not getting updated. It updates only when i restart the ./run.sh script. Do you maybe run some script that restarts the server from time to time ?

**Comment by Feuermurmel** [comment]
That's strange. The application nowhere caches the data in the returned RSS feeds. Whenever a feed is requested, all data is requested using the YouTube API, transformed and delivered. Can you provide the log output that is generated while you refresh the feed in the podcast app?

I'm using both _Podcasts_ from Apple and _Downcast_ and did not yet experience this issue.

**Comment by Feuermurmel** [comment]
I'm closing this now. If you still need help with your issue, please open a new issue. If you could include the full output of the script, that would be great.
